import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Next Example',
  description: 'Generated by Shane',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} container mx-auto bg-slate-800 p-4 text-slate-100`}
      >
        {children}
      </body>
    </html>
  );
}
